# -*- coding: utf-8 -*-
"""e5dd331b-2e75-4a6b-8e6a-1a03b96664d6

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/collektr-351804/locations/us-east1/repositories/e5dd331b-2e75-4a6b-8e6a-1a03b96664d6
"""

import time
import requests
import gzip
from io import BytesIO, StringIO
import pandas as pd
import jwt
from datetime import datetime, date, timedelta
from google.cloud import bigquery
import os

# ===============================
# CONFIG — EDIT THESE VALUES
# ===============================
KEY_ID = "KEY_ID"
ISSUER_ID = "ISSUER_ID"
P8_FILE_PATH = "AUTHKEY"   # ensure this file is uploaded to the notebook environment
VENDOR_NUMBER = "VENDOR_NUMBER"

# If table is empty (no prior dates), backfill from this date (YYYY-MM-DD).
# Set to the earliest date you want to pull from; otherwise set to a conservative launch date.
START_DATE_STR = "2024-12-24"

# How many days back from today is considered "safe" (Apple usually lags).
# Example: SAFE_DELAY_DAYS = 2 -> end_date = today - 2 days
SAFE_DELAY_DAYS = 2

# BigQuery target
BQ_PROJECT = "THE_PROJECT"
BQ_DATASET = "WHAT_DATASET"
BQ_TABLE = "WHAT_TABLE"

# Politeness and token handling
REQUEST_DELAY = 1.0                     # seconds between API requests
TOKEN_RENEW_MARGIN_SECONDS = 60         # regen token if within this many seconds of expiry

# ===============================
# HELPERS: JWT / API / BQ
# ===============================
def generate_jwt(key_id: str = KEY_ID, issuer_id: str = ISSUER_ID, p8_path: str = P8_FILE_PATH, valid_minutes: int = 20):
    """Generate ES256 JWT signed with .p8 private key. Returns (token_string, expiry_timestamp)."""
    with open(p8_path, "r") as f:
        private_key = f.read()
    now = int(time.time())
    exp = now + valid_minutes * 60
    payload = {"iss": issuer_id, "exp": exp, "aud": "appstoreconnect-v1"}
    token = jwt.encode(payload, private_key, algorithm="ES256", headers={"kid": key_id})
    if isinstance(token, bytes):
        token = token.decode("utf-8")
    return token, exp

def fetch_sales_report_for_date(token: str, vendor_number: str, report_date: date):
    """Return pandas DataFrame for the day's sales report, or None if not available."""
    url = "https://api.appstoreconnect.apple.com/v1/salesReports"
    params = {
        "filter[reportDate]": report_date.strftime("%Y-%m-%d"),
        "filter[reportType]": "SALES",
        "filter[reportSubType]": "SUMMARY",
        "filter[frequency]": "DAILY",
        "filter[vendorNumber]": vendor_number
    }
    headers = {"Authorization": f"Bearer {token}"}
    resp = requests.get(url, headers=headers, params=params)
    if resp.status_code != 200:
        print(f"[{report_date}] API returned {resp.status_code} — skipping for now.")
        # Optionally print resp.text for debugging, but can be noisy
        # print(resp.text)
        return None
    # decompress gzipped TSV
    with gzip.open(BytesIO(resp.content), 'rt', encoding='utf-8') as fh:
        txt = fh.read()
    df = pd.read_csv(StringIO(txt), sep="\t")
    df.columns = [c.strip() for c in df.columns]
    df["_report_date_requested"] = report_date
    return df

def get_latest_date_in_bq():
    """Query BigQuery for the max _report_date_requested in the target table. Returns a date or None."""
    client = bigquery.Client(project=BQ_PROJECT)
    q = f"SELECT MAX(_report_date_requested) AS max_date FROM `{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE}`"
    job = client.query(q)
    rows = list(job.result())
    if not rows:
        return None
    max_date = rows[0].get("max_date")
    # max_date can be a datetime.date or datetime.datetime; handle both
    if max_date is None:
        return None
    if isinstance(max_date, datetime):
        return max_date.date()
    return max_date

def delete_existing_date(report_date: date):
    """DELETE rows for the given date to avoid duplicates."""
    client = bigquery.Client(project=BQ_PROJECT)
    q = f"""
    DELETE FROM `{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE}`
    WHERE _report_date_requested = DATE('{report_date}')
    """
    client.query(q).result()
    print(f"Deleted existing rows for {report_date}")

def upload_to_bigquery(df: pd.DataFrame):
    """Upload DataFrame to BigQuery (append)."""
    client = bigquery.Client(project=BQ_PROJECT)
    table_id = f"{BQ_PROJECT}.{BQ_DATASET}.{BQ_TABLE}"
    df_bq = df.copy()
    df_bq.columns = [c.strip().replace(" ", "_").replace("/", "_").lower() for c in df_bq.columns]
    job = client.load_table_from_dataframe(
        df_bq,
        table_id,
        job_config=bigquery.LoadJobConfig(write_disposition="WRITE_APPEND")
    )
    job.result()
    print(f"Uploaded {len(df_bq)} rows to {table_id}")

# ===============================
# MAIN: incremental backfill loop
# ===============================
def run_backfill():
    # compute safe end date
    today = date.today()
    safe_end_date = today - timedelta(days=SAFE_DELAY_DAYS)

    # find start date (one day after max in BQ), or fallback to START_DATE_STR
    latest_in_bq = get_latest_date_in_bq()
    if latest_in_bq:
        start_date = latest_in_bq + timedelta(days=1)
        print("Latest date in BigQuery:", latest_in_bq, " -> starting from", start_date)
    else:
        start_date = datetime.strptime(START_DATE_STR, "%Y-%m-%d").date()
        print("No existing data in BigQuery. Starting from configured START_DATE:", start_date)

    if start_date > safe_end_date:
        print("Nothing to do: start_date > safe_end_date (", start_date, ">", safe_end_date, ")")
        return

    # generate first JWT
    token, token_exp = generate_jwt()
    print("Initial JWT expiry:", datetime.fromtimestamp(token_exp).isoformat())

    current = start_date
    total_rows = 0
    while current <= safe_end_date:
        # regenerate token if close to expiry
        now_ts = int(time.time())
        if now_ts + TOKEN_RENEW_MARGIN_SECONDS >= token_exp:
            token, token_exp = generate_jwt()
            print("Regenerated JWT; new expiry:", datetime.fromtimestamp(token_exp).isoformat())

        print(f"Attempting to fetch {current} ...")
        df = fetch_sales_report_for_date(token, VENDOR_NUMBER, current)
        if df is None or df.empty:
            print(f"[{current}] No report or empty — skipping.")
        else:
            # safe write: delete existing date first, then upload
            try:
                delete_existing_date(current)
            except Exception as e:
                print("Warning: delete_existing_date failed:", e)
            try:
                upload_to_bigquery(df)
                total_rows += len(df)
            except Exception as e:
                print("ERROR uploading to BigQuery for", current, ":", e)

        time.sleep(REQUEST_DELAY)
        current += timedelta(days=1)

    print("Backfill finished. Total rows uploaded this run:", total_rows)

# allow running directly in notebook
if __name__ == "__main__":
    run_backfill()